#!/usr/bin/env python3
"""Generate a stable web-game version that changes only with web source."""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parent
WEB = ROOT / "web"
SOURCES = (WEB / "index.html", WEB / "style.css", WEB / "game.js")
OUTPUT = WEB / "version.js"


def source_hash() -> str:
    digest = hashlib.sha256()
    for source in SOURCES:
        digest.update(source.name.encode("ascii"))
        digest.update(b"\0")
        digest.update(source.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()[:12]


def main() -> None:
    fingerprint = source_hash()
    if OUTPUT.exists() and f'"source": "{fingerprint}"' in OUTPUT.read_text():
        return

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S UTC")
    OUTPUT.write_text(
        "// Generated by build_web_version.py. Do not edit manually.\n"
        f'window.MAKIHYPPY_VERSION = {{ "source": "{fingerprint}", "built": "{timestamp}" }};\n'
    )


if __name__ == "__main__":
    main()
